INSERT INTO users(name, password, email) VALUES ('Librarian', '$2a$10$AOTDZBMm5tuAhhuGZ.9HG.qHWD7dAzAD7fr29nbBDsQA2f3WoUrC6', 'librarian@example.com');

INSERT INTO books(isbn, title, author, state) VALUES ('1', 'Hamlet', 'William Shakespeare', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('3', 'Mary', 'Vladimir Nabokov', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('3', 'Mary', 'Vladimir Nabokov', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('2', 'IT', 'Stephen King', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('2', 'IT', 'Stephen King', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('1', 'Hamlet', 'William Shakespeare', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('4', 'The Stand', 'Stephen King', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('4', 'The Stand', 'Stephen King', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('4', 'The Stand', 'Stephen King', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('5', 'Harry Potter And The Chamber of Secrets', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('5', 'Harry Potter And The Chamber of Secrets', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('5', 'Harry Potter And The Chamber of Secrets', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('6', 'Star Wars: A New Hope', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('6', 'Star Wars: A New Hope', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('6', 'Star Wars: A New Hope', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('7', 'Star Wars: The Empire Strikes Back', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('7', 'Star Wars: The Empire Strikes Back', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('7', 'Star Wars: The Empire Strikes Back', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('8', 'Star Wars: Return of the Jedi', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('8', 'Star Wars: Return of the Jedi', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('8', 'Star Wars: Return of the Jedi', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('9', 'Star Wars: The Phantom Menace', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('9', 'Star Wars: The Phantom Menace', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('9', 'Star Wars: The Phantom Menace', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('10', 'Star Wars: Attack of the Clones', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('10', 'Star Wars: Attack of the Clones', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('10', 'Star Wars: Attack of the Clones', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('11', 'Star Wars: Revenge of the Sith', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('11', 'Star Wars: Revenge of the Sith', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('11', 'Star Wars: Revenge of the Sith', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('12', 'Harry Potter And The Philisophers Stone', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('12', 'Harry Potter And The Philisophers Stone', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('12', 'Harry Potter And The Philisophers Stone', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('13', 'Harry Potter And The Prizoner of Azkaban', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('13', 'Harry Potter And The Prizoner of Azkaban', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('13', 'Harry Potter And The Prizoner of Azkaban', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('14', 'Harry Potter And The Goblet of Fire', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('14', 'Harry Potter And The Goblet of Fire', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('14', 'Harry Potter And The Goblet of Fire', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('15', 'Harry Potter And The Order of the Phoenix', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('15', 'Harry Potter And The Order of the Phoenix', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('15', 'Harry Potter And The Order of the Phoenix', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('16', 'Harry Potter And The Half-Blood Prince', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('16', 'Harry Potter And The Half-Blood Prince', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('16', 'Harry Potter And The Half-Blood Prince', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('17', 'Harry Potter And The Deathly Hallows', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('17', 'Harry Potter And The Deathly Hallows', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('17', 'Harry Potter And The Deathly Hallows', 'J. K. Rowling', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('18', 'The Call of Cthulhu', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('18', 'The Call of Cthulhu', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('18', 'The Call of Cthulhu', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('19', 'The Rats in the Walls', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('19', 'The Rats in the Walls', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('19', 'The Rats in the Walls', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('20', 'At the Mountains of Madness', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('20', 'At the Mountains of Madness', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('20', 'At the Mountains of Madness', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('21', 'The Shadow over Innsmouth', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('21', 'The Shadow over Innsmouth', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('21', 'The Shadow over Innsmouth', 'H.P. Lovecraft', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('6', 'Star Wars: A New Hope', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('7', 'Star Wars: The Empire Strikes Back', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('8', 'Star Wars: Return of the Jedi', 'George Lucas', 0);
INSERT INTO books(isbn, title, author, state) VALUES ('9', 'Star Wars: The Phantom Menace', 'George Lucas', 0);
